In [1]:
import numpy as np
v=np.array([[4,5,6]])
w=np.array([[10,20,30]]).T
print(v+w)
print(v.shape)
print(w.shape)

[[14 15 16]
 [24 25 26]
 [34 35 36]]
(1, 3)
(3, 1)


In [6]:
# 1차원 배열
vector = np.array([1, 2, 3])

# 3차원 배열
tensor = np.array([[[1, 2, 3]   , [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])

print(vector.shape)
print(tensor.shape)
print(vector+tensor)


(3,)
(2, 2, 3)
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]


In [4]:
v=np.array([1,2,3,7,8,9])
v_dim=len(v)
v_mag=np.linalg.norm(v)
print(v_dim)
print(v_mag)

6
14.422205101855956


In [8]:
a=np.array([[1,2,3,4]])
b=np.array([[5,6,7,8]]).T
np.dot(a,b)

ValueError: shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)