In [1]:
import numpy as np
np.__version__

'1.26.4'

In [14]:
a=np.full((2,3),[1,2,3])
a

array([[7, 7, 7],
       [7, 7, 7]])

In [7]:
b=np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [8]:
a@b

array([[12,  6],
       [12,  6]])

In [9]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [10]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])