In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
from numpy import arange

x=arange(1,10).reshape(3,3)

x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y= arange(-1,2)
y

array([-1,  0,  1])

In [4]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [5]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])